name = "embedding_db"
description = """
 Creates a database of embeddings. (A database is just a different way to store information, in this cases this stores documents in a way that makes it easy to find other documents with similar meanings)

 When using this embedding database, you must use the same model to generate the embeddings you insert into this database.
"""
package_version = "0.1"
binding_version = "0.1"
