name = "format"
description = """
 Formats some text by replacing any instances of {} in order with the texts passed in.

 Example:

 template: \"Who is {}?\"
 inputs: \"queen of england\"

 result: Who is the queen of england?
"""
package_version = "0.1"
binding_version = "0.1"
