name = "search"
description = """
 Searches an embedding database for the closest embedding

 This node requires that the Embedding Database and the Embedding use the same model.

 Returns text with documents separated with newlines.
"""
package_version = "0.1"
binding_version = "0.1"
