name = "embedding"
description = """
 Creates embeddings for some text.

 An embedding is a representation of something like the \"meaning\" of some text. You can use embeddings with embedding databases to find documents similar to anther document.
"""
package_version = "0.1"
binding_version = "0.1"
